Feature/components
MarilenaRoque/magicians-calculator pull request #2
Opened 2021-01-05 22:18 UTC by MarilenaRoque

# #2 Milestone is completed :rocket:
  - Build Components: App, Display, ButtonPanel and Button
  - App renders Display and ButtonPanel
  - Display receives result and result has its validations and default
  - Button receives name and name has its validations
  - ButtonPanel renders groups of Buttons
  - Updating README.md

2021-01-05 22:56 UTC, mikenath223 requested changes
### Hello @MarilenaRoque  👋

**You've done pretty well here. Grouping the buttons and then mapping through them was a good idea.** 👌

However, let's make a few changes.

- Please refer to comments on your code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2021-01-05 23:00 UTC, mikenath223 commented on src/components/App.js
> +  );
- [ ] It's better to wrap these two components using React.Fragment short syntax. Since there is no need to add an extra div node.

2021-01-05 23:32 UTC, MarilenaRoque commented
# Change Required Implemented :rocket:

- [X] It's better to wrap these two components using React.Fragment short syntax. Since there is no need to add an extra div node.

2021-01-06 00:28 UTC, bellom approved these changes
## Hi @MarilenaRoque  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-01-06 00:28 UTC, bellom commented on src/components/App.js
> +    </fragment>
### [Optional]
Good job making the changes from the previous reviewer.

perhaps we could shorten the code.

```
    <>
      <Display />
      <ButtonPanel />
    </>
```

2021-01-06 02:33 UTC, merged

2021-01-06 02:34 UTC, MarilenaRoque commented
# Thank you for the Review, @bellom ! :rocket: